version: '3.8'

services:
  nestjs-backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
      - redis-cache
    environment:
      - DB_HOST=postgres-db
      - REDIS_HOST=redis-cache

  postgres-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"

  redis-cache:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
